### ISSUE TITLE
Ukuu 19.07.02 unable to install new kernels

### ISSUE THREAD

**Issue by jdferron** [teejee2008/ukuu-plus#29]
Ukuu 19.07.02 is unable to install any new kernel.  I've tried to install 5.1.17 - 5.1.19 and 5.2.2 and none of the kernel will download and install. 

For example, looking 5.1.19, it looks like the kernel packages exist: https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.1.9/

This previously worked on v19.07.

**Comment by teejee2008** [comment]
Kernel packages have failed to build on the Ubuntu server for 5.1.17, 5.1.18, 5.2 and 5.2.1

https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.2/

If you see the above page it says that "build failed for amd64". Since packages are not available, it's not possible for Ukuu to install them.

We need to wait for someone from the Ubuntu team to fix the builds.

**Comment by teejee2008** [comment]
The link you have posted is for 5.1.9. Check the page for 5.1.19
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.1.19/

**Comment by teejee2008** [comment]
The following Launchpad page has updates for this issue.
https://bugs.launchpad.net/bugs/1830961
