### ISSUE TITLE
Unable to install on Peppermint 10

### ISSUE THREAD

**Issue by Nitrosnfr** [teejee2008/ukuu-plus#42]
This is output from trying to install.....
The following packages have unmet dependencies:
 ukuu-gtk : Depends: ukuu (>= 19.10) but 18.5.1-0~201805120527~ubuntu18.04.1 is to be installed
            Recommends: vimix-gtk-theme but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

> E: Another process is using the package manager! 
> E: Close the other process, or retry after sometime

**Comment by teejee2008** [comment]
Remove the PPA for free version:

sudo add-apt-repository --remove ppa:teejee2008/ppa

Then run the install script again.

Your package manager was being used by another process when you ran the script. Try running after sometime if you get the error.

**Comment by Nitrosnfr** [comment]
Get the exact same result.Free PPA wasn't installed and package manager was
not being used by anything else.Is it a possible it's not compatible with
this linux version... *Peppermint 10 Respin* (20191210), the latest
iteration of our operating system. Based on the 18.04 LTS

**Comment by ZebedeeBoss** [comment]
I too am having the exact same problem 
`> Installing packages... 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ukuu is already the newest version (18.5.1-0~201805120527~ubuntu18.04.1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 ukuu-gtk : Depends: ukuu (>= 19.10) but 18.5.1-0~201805120527~ubuntu18.04.1 is to be installed
            Recommends: vimix-gtk-theme but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

> E: Another process is using the package manager! 
> E: Close the other process, or retry after sometime 
zebedee@threadripper-2950x ~ $`

I upgraded to the paid version as 4.6 kernels will not install on the free version due to an nvidia problem.  Any help gratefully appreciated.  It was about time I bought your UKUU to support you anyway.  It has been great up until 4.6 kernel then these nvidia issues ensued

**Comment by ZebedeeBoss** [comment]
This was following a reboot, so I know the package manager was not busy

**Comment by teejee2008** [comment]
This is an issue with Peppermint OS. Peppermint has the free version of Ukuu in its repository (v18.5.1) and it is pinned with a higher priority. This prevents the installation of newer versions of Ukuu.

As a workaround, run the install script and then use the following command to install the paid version:
`sudo apt install ukuu-gtk ukuu=19.12`

**Comment by ZebedeeBoss** [comment]
Thank you - that got it installed.   However it is still suffering the nvidia build failure...  I will wait for nvidia/ubuntu to catch up.  Thank you for your response

**Comment by XxxSpiritvsxxX** [comment]
Just installed it right now in Peppermint OS Repsin, my favourite Linux Distro..

No issues at all. The e-mailed install script worked in the first try for me. No errors.
Updated the previous free version.
Running Kernel 5.4.7 now with no issues to report.
