### ISSUE TITLE
install.sh leaves shell w/root prompt

### ISSUE THREAD

**Issue by JBHoren** [teejee2008/ukuu-plus#5]
Just so. I downloaded the 32-bit package, extracted the contents, and ran the included install.sh script -- perfect. That was a few days ago.

Today, I decided to install the latest 4.19 kernel, using ukuu, of course. As with previous versions, it opened an interactive window, and everything proceeded as expected... right up until the end, when it finished and left the window... with a fully-functional root prompt.

Thought I should mention it.

**Comment by teejee2008** [comment]
This is as designed. The interactive window has an embedded terminal that runs as root for installing the packages. The window is kept open so that any error messages can be viewed by the user. You can also run any admin commands that you need to run after the installation has finished. Clicking the "Finish" button closes the window.

I can hide the terminal and display a simple progress bar instead, but most people prefer to see the output messages.

**Comment by teejee2008** [comment]
This is changed in v19.04. Terminal will not accept input after the installation/removal is completed
