### ISSUE TITLE
Problem with update kernel

### ISSUE THREAD

**Issue by dkgnim** [teejee2008/ukuu-plus#60]
This kernel cannot be installed as the build is broken. Please wait for the next kernel update.
I'm to try to install the latest kernel

**Comment by teejee2008** [comment]
UKUU installs packages from Ubuntu's server. Packages are not available for the latest kernels due to build errors. Ubuntu developers normally take a week or two to fix the build issues.

You can check status on following page:
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11.2/

Try installing again after a few days.
